spring.application.name=finance-backend

# ===============================
# DB - PostgreSQL
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# Base URL
# ===============================
server.port=${SERVER_PORT:9000}
app.frontend-url=${FRONTEND_URL:http://localhost:3000}


# ===============================
# Configurations
# ===============================
spring.config.import=optional:file:.env[.properties]

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

# ===============================
# Email (DEV MODE)
# ===============================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===============================
# Logs
# ===============================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=ERROR
spring.output.ansi.enabled=ALWAYS
logging.file.name=logs/talenthub.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30